---

- hosts: all
  become: true
  tasks:

    - name: install apache on server
      ansible.builtin.dnf:
       name: httpd
       state: present

    - name: start apache
      service:    
         name: httpd
         state: started  
    - name: copy the file from location to server
      ansible.builtin.copy:
           src: index.html
           dest: /var/www/html
           owner: root
           group: root
           mode: 0644    
