---

- hosts: all
  become: true
  tasks:

    - name: install apache on server
      ansible.builtin.dnf:
       name: httpd
       state: present
      when: ansible_distribution == "CentOS"   

    - name: install apache on server
      ansible.builtin.apt:
       name: apache2
       state: present
      when: ansible_distribution == "Ubuntu"

    - name: start apache
      service:
         name: httpd
         state: started
      when: ansible_distribution == "CentOS"     

    - name: start apache
      service:
         name: apache2
         state: started
      when: ansibe_distribution == "Ubuntu"     
       
       
    - name: copy the file from location to server
      ansible.builtin.copy:
           src: index.html
           dest: /var/www/html
           owner: root
           group: root
           mode: 0644

    - name: add port 80 for centos server
      ansible.posix.firewalld:
        port: 80/tcp
        permanent: true
        zone: public
        state: enabled
      when: ansible_distribution == "CentOS"     
